---
title: "heritability calculation"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_knit$set(root.dir=normalizePath('../../')) 
```



```{r}
library(readr)
cwd <- read.csv("../cache/cob_length_2018_2019_N.csv")
head(cwd)
class(cwd$meancw)
#View(cwd)
head(cwd)
tail(cwd)
dim(cwd)

```



```{r}
install.packages("tidyverse")
update.packages('rlang')
install.packages("devtools")
devtools::install_github("jyanglab/g3tools")
library("g3tools")
```

```{r}
install.packages("scales")
ls(getNamespace("g3tools"), all.names=FALSE)
```


```{r}
options(stringsAsFactors = FALSE) 
install.packages("devtools")
install.packages("Rtools")
library(devtools)
devtools::install_github("jyanglab/g3tools")
devtools::install_github("r-lib/devtools")

```




```{r}
ls(getNamespace("g3tools"), all.names=FALSE)

help("get_BLUP")
help("get_H2")

```



```{r}
pheno_cwd <- cwd 


#install.packages("Ime4")
library(lme4)
```

```{r}
heritability <- get_BLUP(data = pheno_cwd, model = meancw ~ (1 | Genotype) + (1 | year) + (1 | block) + (1 | sb) + (1 | spb) + (1
  | Genotype:year) + (1 | Genotype:block), which.factor = "Genotype", outfile = "heritability.csv")

```


```{r}
summary(heritability)
```


```{r}
Vg= 2.20425
Ve= 2.20963
Vgxy= 0.93726
Vgxb= 0.06109
Ny = 2
Nb = 2
NyxNb = 4


H2 = Vg/ (Vg + (Vgxy/Ny) + (Vgxb/Nb) + (Ve/NyxNb))
H2 # 0.6770158



vg = 2.20425
ve = 2.20963
H2 = vg/(vg+ve/4) #Since I have 2 replications and 2 years. So, it is 2x2= 4
H2 #  0.7996097

```


###Low Nitrogen
```{r}
library(readr)
cwd_No <- read.csv("../cache/cob_length_2018_2019_noN.csv")
head(cwd_No)
class(cwd_No$meancw)
View(cwd_No)
head(cwd_No)
tail(cwd_No)
dim(cwd_No)

```



```{r}
install.packages("tidyverse")
update.packages('rlang')
install.packages("devtools")
devtools::install_github("jyanglab/g3tools")
library("g3tools")
```

```{r}
install.packages("scales")
ls(getNamespace("g3tools"), all.names=FALSE)
```


```{r}
options(stringsAsFactors = FALSE) 
install.packages("devtools")
install.packages("Rtools")
library(devtools)
devtools::install_github("jyanglab/g3tools")
devtools::install_github("r-lib/devtools")

```


```{r}
ls(getNamespace("g3tools"), all.names=FALSE)

#help("get_BLUP")
#help("get_H2")

```



```{r}
pheno_noN <- cwd_No 


install.packages("Ime4")
library(lme4)
```

```{r}
heritability <- get_BLUP(data = pheno_noN, model = meancw ~ (1 | Genotype) + (1 | year) + (1 | block) + (1 | sb) + (1 | spb) + (1
  | Genotype:year) + (1 | Genotype:block), which.factor = "Genotype", outfile = "heritability.csv")

```


```{r}
summary(heritability)
```


```{r}
Vg= 1.481289
Ve= 2.838897
Vgxy= 1.216116
Vgxb= 0
Ny = 2
Nb = 2
NyxNb = 4


H2 = Vg/ (Vg + (Vgxy/Ny) + (Vgxb/Nb) + (Ve/NyxNb))
H2 # 0.5292073



vg = 1.481289
ve = 2.838897
H2 = vg/(vg+(ve/4)) #Since I have 2 replications and 2 years. So, it is 2x2= 4
H2 #  0.6760749

```
